### ISSUE TITLE
mgvv diff: reporting bugs

### ISSUE THREAD

**Issue by dangunter** [materialsproject/pymatgen-db#17]
CRITICAL [mg] In 'diff' command: Runtime error: Not a number: collection=new key=3725 e_above_hull='None'(builder_env)-bash-3.2

$ mgvv diff -k "snlgroup_id_final" -p 'icsd_ids,task_id' -m -n "efermi=+-0.01" mprod.json mdev.json
Traceback (most recent call last):

  File "/global/u1/w/weichen1/builder_env/bin/mgvv", line 10, in <module>

    execfile(__file__)

  File "/global/u1/w/weichen1/builder_env/pymatgen-db/scripts/mgvv", line 619, in <module>

    sys.exit(main())

  File "/global/u1/w/weichen1/builder_env/pymatgen-db/scripts/mgvv", line 610, in main

    return args.func(args, *args.func_args)

  File "/global/u1/w/weichen1/builder_env/pymatgen-db/scripts/mgvv", line 264, in command_diff

    text = make_report(args.format or "text")

  File "/global/u1/w/weichen1/builder_env/pymatgen-db/scripts/mgvv", line 250, in <lambda>

    make_report = lambda f: getattr(report, "Diff{}Formatter".format(f.title()))(meta, **fmt_kwargs).format(r)

  File "/global/u1/w/weichen1/builder_env/pymatgen-db/matgendb/vv/report.py", line 709, in format

    self.sort_rows(rows, section)

  File "/global/u1/w/weichen1/builder_env/pymatgen-db/matgendb/vv/report.py", line 482, in sort_rows

    rows.sort(key=itemgetter(sort_key))

KeyError: 'delta'

**Comment by dangunter** [comment]
I think this old fix actually took care of it. Reopen if the bug resurfaces.
