### ISSUE TITLE
mgdb runserver failing with AppRegistryNotReady error

### ISSUE THREAD

**Issue by migueldiascosta** [materialsproject/pymatgen-db#33]
Using a clean virtualenv with python 2.7 and "pip install -r requirements.txt", when I try to run _mgdb runserver_ it fails with an AppRegistryNotReady error.

(This is usually attributed to calling _django.core.handlers.wsgi:WSGIHandler_, which was used in django 1.6, instead of _django.core.wsgi:get_wsgi_application_ which is used in 1.7, but webui/wsgi.py is using the latter, and I am using 1.7)

I can reproduce the error in a vanilla django site if I execute runserver using _call_command_, as in _mgdb_, instead of the default _execute_from_command_line_.

The difference seems to be that _execute_from_command_line_ eventually calls _django.setup_, which populates the AppRegistry, while _call_command_ doesn't.

Indeed, I can get the vanilla django site to work with _call_command_ if I invoke _django.setup_ just before.

Should _mgdb_ call _django.setup_ explicitly? On the other hand, I do wonder why nobody else seems to have this issue...

**Comment by kamal-ch** [comment]
Any solution to this problem yet? I get similar error message:
Traceback (most recent call last):
  File "/apps/python/2.7.8/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/apps/python/2.7.8/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kamal/Venv_pymatgen/lib/python2.7/site-packages/django/core/management/__init__.py", line 99, in call_command
    command = load_command_class(app_name, name)
  File "/home/kamal/Venv_pymatgen/lib/python2.7/site-packages/django/core/management/__init__.py", line 39, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/apps/python/2.7.8/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/kamal/Venv_pymatgen/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 16, in <module>
    from django.db.migrations.executor import MigrationExecutor
  File "/home/kamal/Venv_pymatgen/lib/python2.7/site-packages/django/db/migrations/executor.py", line 7, in <module>
    from .loader import MigrationLoader
  File "/home/kamal/Venv_pymatgen/lib/python2.7/site-packages/django/db/migrations/loader.py", line 10, in <module>
    from django.db.migrations.recorder import MigrationRecorder
  File "/home/kamal/Venv_pymatgen/lib/python2.7/site-packages/django/db/migrations/recorder.py", line 12, in <module>
    class MigrationRecorder(object):
  File "/home/kamal/Venv_pymatgen/lib/python2.7/site-packages/django/db/migrations/recorder.py", line 26, in MigrationRecorder
    class Migration(models.Model):
  File "/home/kamal/Venv_pymatgen/lib/python2.7/site-packages/django/db/models/base.py", line 94, in __new__
    app_config = apps.get_containing_app_config(module)
  File "/home/kamal/Venv_pymatgen/lib/python2.7/site-packages/django/apps/registry.py", line 239, in get_containing_app_config
    self.check_apps_ready()
  File "/home/kamal/Venv_pymatgen/lib/python2.7/site-packages/django/apps/registry.py", line 124, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
AppRegistryNotReady: Apps aren't loaded yet.

**Comment by shyuep** [comment]
You were using a new DJango, while pymatgen-db specially states 1.7. In any case, I have upgraded Django and fixed the problem.

**Comment by kamal-ch** [comment]
I

**Comment by kamal-ch** [comment]
I figured that while "pip install pymatgen-db" it gives the following error
message. Am I missing some config settings?

Compiling /tmp/pip_build_kamal/django/django/conf/app_template/apps.py ...
  File "/tmp/pip_build_kamal/django/django/conf/app_template/apps.py", line
4
    class {{ camel_case_app_name }}Config(AppConfig):
          ^
SyntaxError: invalid syntax

Compiling /tmp/pip_build_kamal/django/django/conf/app_template/models.py ...
  File "/tmp/pip_build_kamal/django/django/conf/app_template/models.py",
line 1
    {{ unicode_literals }}from django.db import models
                             ^
SyntaxError: invalid syntax

Successfully installed pymatgen-db django
Cleaning up...

**Comment by shyuep** [comment]
This is a django problem. I have no idea what it is


Shyue Ping

On December 4, 2015 at 7:35:44 AM, kamal-ch (notifications@github.com) wrote:

I figured that while "pip install pymatgen-db" it gives the following error
message. Am I missing some config settings?

Compiling /tmp/pip_build_kamal/django/django/conf/app_template/apps.py ...
File "/tmp/pip_build_kamal/django/django/conf/app_template/apps.py", line
4
class {{ camel_case_app_name }}Config(AppConfig):
^
SyntaxError: invalid syntax

Compiling /tmp/pip_build_kamal/django/django/conf/app_template/models.py ...
File "/tmp/pip_build_kamal/django/django/conf/app_template/models.py",
line 1
{{ unicode_literals }}from django.db import models
^
SyntaxError: invalid syntax

Successfully installed pymatgen-db django
Cleaning up...
